/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.sql.*;
import javax.swing.JOptionPane;
import model.Database;
import model.Anggota;
import model.Mahasiswa;
import model.PJ;


/**
 *
 * @author yasmi
 */
public class formLogin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public formLogin() {
        Database.connect();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
//    public static formLogin1 getInstance(){
//        return new formLogin1();
//    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtLoginnim = new javax.swing.JTextField();
        passLogin = new javax.swing.JPasswordField();
        btnXlogin = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        cbRole = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtLoginnim.setBackground(new java.awt.Color(187, 147, 48));
        txtLoginnim.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        txtLoginnim.setBorder(null);
        txtLoginnim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLoginnimActionPerformed(evt);
            }
        });
        getContentPane().add(txtLoginnim, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 560, 60));

        passLogin.setBackground(new java.awt.Color(187, 147, 48));
        passLogin.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        passLogin.setBorder(null);
        passLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passLoginActionPerformed(evt);
            }
        });
        getContentPane().add(passLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 360, 560, 60));

        btnXlogin.setBackground(new java.awt.Color(255, 249, 234));
        btnXlogin.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnXlogin.setForeground(new java.awt.Color(100, 90, 65));
        btnXlogin.setText("X");
        btnXlogin.setBorder(null);
        btnXlogin.setBorderPainted(false);
        btnXlogin.setContentAreaFilled(false);
        btnXlogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXloginActionPerformed(evt);
            }
        });
        getContentPane().add(btnXlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 20, -1, -1));

        btnLogin.setContentAreaFilled(false);
        btnLogin.setBackground(new java.awt.Color(228, 198, 122));
        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(100, 90, 65));
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 220, 60));

        cbRole.setBackground(new java.awt.Color(187, 147, 48));
        cbRole.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Role", "Penanggung Jawab", "Anggota" }));
        cbRole.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        cbRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbRoleActionPerformed(evt);
            }
        });
        getContentPane().add(cbRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 230, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGIN (11).png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        try {
            String nim = txtLoginnim.getText();
            String password = passLogin.getText();
        
        if (nim.equals("") || password.equals("") || cbRole.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Pastikan semua data terisi!");
            return;
            } else {
                if (Database.connect() != null) {
                    if (cbRole.getSelectedItem().equals("Penanggung Jawab")){
                        if (PJ.loginPJ(nim, password)) {
                            JOptionPane.showMessageDialog(null, "Login Berhasil!");
                            formCRUDadmin formCRUDadmin = new formCRUDadmin();
                            formCRUDadmin.setVisible(true);
                            formCRUDadmin.pack();
                            formCRUDadmin.setLocationRelativeTo(null);
                            formCRUDadmin.setDefaultCloseOperation(formCRUDadmin.EXIT_ON_CLOSE);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(null, "Login Gagal!");
                        }
                    } else if (cbRole.getSelectedItem().equals("Anggota")) {
                        if (Anggota.loginAnggota(nim, password)) {
                                JOptionPane.showMessageDialog(null, "Login Berhasil!");
                                HalamanAwalAnggota halamanAwalAnggota = new HalamanAwalAnggota();
                                halamanAwalAnggota.setVisible(true);
                                halamanAwalAnggota.pack();
                                halamanAwalAnggota.setLocationRelativeTo(null);
                                halamanAwalAnggota.setDefaultCloseOperation(HalamanAwalAnggota.EXIT_ON_CLOSE);
                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(null, "Login Gagal!");
                            }
                    }
                } 
            } 
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "NIM atau Password salah!", "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnLoginActionPerformed

    private void passLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passLoginActionPerformed
        
    }//GEN-LAST:event_passLoginActionPerformed

    private void txtLoginnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLoginnimActionPerformed
        
    }//GEN-LAST:event_txtLoginnimActionPerformed

    private void btnXloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXloginActionPerformed
        formTampilanAkhir formTampilanAkhir = new formTampilanAkhir();
        formTampilanAkhir.setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_btnXloginActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked

    }//GEN-LAST:event_btnLoginMouseClicked

    private void cbRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbRoleActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                formLogin login = new formLogin();
                login.setVisible(true);
                login.pack();
                login.setLocationRelativeTo(null);
                login.setDefaultCloseOperation(formLogin.EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnXlogin;
    private javax.swing.JComboBox<String> cbRole;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField passLogin;
    private javax.swing.JTextField txtLoginnim;
    // End of variables declaration//GEN-END:variables
}
