/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;
import model.*;

/**
 *
 * @author yasmi
 */
public class formDaftarTugasUser extends javax.swing.JFrame {

    /**
     * Creates new form DaftarTugasUser
     */
    public formDaftarTugasUser() {
        initComponents();
        Database.connect();
        table();
        addTableClickListener();
    }

private void addTableClickListener() {
    tabelDaftartugasuser.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int row = tabelDaftartugasuser.getSelectedRow(); // Baris yang dipilih
            
            if (row != -1) {
                // Ambil deskripsi tugas dari kolom ke-3 (indeks 3)
                String deskripsi_tugas = tabelDaftartugasuser.getValueAt(row, 3).toString();
                
                // Set deskripsi tugas ke text area atau text field
                txtDeskripsi.setText(deskripsi_tugas);
            }
        }
    });
}

    
    void table() {
        DefaultTableModel model = new DefaultTableModel(){
          @Override
          public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        model.addColumn("ID Tugas");
        model.addColumn("Nama Mata Kuliah");
        model.addColumn("Nama Tugas");
        model.addColumn("Deskripsi Tugas");
        model.addColumn("Tenggat Waktu");
        model.addColumn("Skala Prioritas");
        model.addColumn("Status Tugas");
        
        try {
            Statement statement = Database.connection.createStatement();
            ResultSet resultSet = statement.executeQuery("SELECT * FROM tugas");
            
            while (resultSet.next()) {
                model.addRow(new Object[] {
                    resultSet.getString("id_tugas"),
                    resultSet.getString("nama_matkul"),
                    resultSet.getString("nama_tugas"),
                    resultSet.getString("deskripsi_tugas"),
                    resultSet.getString("tenggat_waktu"),
                    resultSet.getString("skala_prioritas"),
                    resultSet.getString("status_tugas")
                });
                tabelDaftartugasuser.setModel(model);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTenggat = new javax.swing.ButtonGroup();
        cbNamamatkuluser = new javax.swing.JComboBox<>();
        cbPengurutan = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelDaftartugasuser = new javax.swing.JTable();
        btnKeluarUser = new javax.swing.JButton();
        btnRefreshuser = new javax.swing.JButton();
        btnUrut = new javax.swing.JButton();
        btnLihat = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDeskripsi = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbNamamatkuluser.setBackground(new java.awt.Color(100, 90, 65));
        cbNamamatkuluser.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        cbNamamatkuluser.setForeground(new java.awt.Color(255, 249, 234));
        cbNamamatkuluser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Mata Kuliah", "Pemrograman Berbasis Objek", "Desain Manajemen Jaringan Komputer", "Desain Manajemen Proses Bisnis", "Riset Operasi", "Interaksi Manusia dan Komputer", "Desain Basis Data", "Dasar-Dasar Pengembangan Perangkat Lunak", "Semua mata kuliah" }));
        cbNamamatkuluser.setBorder(null);
        getContentPane().add(cbNamamatkuluser, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 320, 40));

        cbPengurutan.setBackground(new java.awt.Color(100, 90, 65));
        cbPengurutan.setFont(new java.awt.Font("Calibri", 0, 20)); // NOI18N
        cbPengurutan.setForeground(new java.awt.Color(255, 249, 234));
        cbPengurutan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Skala Prioritas Tinggi ke Rendah", "Skala Prioritas Rendah ke Tinggi", "Nama Tugas A-Z", "Nama Tugas Z-A" }));
        cbPengurutan.setBorder(null);
        cbPengurutan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPengurutanActionPerformed(evt);
            }
        });
        getContentPane().add(cbPengurutan, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 320, 40));

        tabelDaftartugasuser.setBackground(new java.awt.Color(228, 198, 122));
        tabelDaftartugasuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nama Mata Kuliah", "Nama Tugas", "Deskripsi Tugas", "Tenggat Deadline", "Skala Prioritas", "Status Tugas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelDaftartugasuser.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tabelDaftartugasuser);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 1120, 290));

        btnKeluarUser.setBackground(new java.awt.Color(228, 198, 122));
        btnKeluarUser.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnKeluarUser.setForeground(new java.awt.Color(100, 90, 65));
        btnKeluarUser.setBorder(null);
        btnKeluarUser.setBorderPainted(false);
        btnKeluarUser.setContentAreaFilled(false);
        btnKeluarUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarUserMouseClicked(evt);
            }
        });
        btnKeluarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarUserActionPerformed(evt);
            }
        });
        getContentPane().add(btnKeluarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 30, 110, 40));

        btnRefreshuser.setBackground(new java.awt.Color(228, 198, 122));
        btnRefreshuser.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnRefreshuser.setForeground(new java.awt.Color(100, 90, 65));
        btnRefreshuser.setBorder(null);
        btnRefreshuser.setBorderPainted(false);
        btnRefreshuser.setContentAreaFilled(false);
        btnRefreshuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshuserActionPerformed(evt);
            }
        });
        getContentPane().add(btnRefreshuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 120, 40));

        btnUrut.setBackground(new java.awt.Color(228, 198, 122));
        btnUrut.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        btnUrut.setForeground(new java.awt.Color(100, 90, 65));
        btnUrut.setBorder(null);
        btnUrut.setBorderPainted(false);
        btnUrut.setContentAreaFilled(false);
        btnUrut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUrutActionPerformed(evt);
            }
        });
        getContentPane().add(btnUrut, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 240, 120, 30));

        btnLihat.setBorder(null);
        btnLihat.setContentAreaFilled(false);
        btnLihat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatActionPerformed(evt);
            }
        });
        getContentPane().add(btnLihat, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 173, 120, 40));

        txtDeskripsi.setColumns(20);
        txtDeskripsi.setLineWrap(true);
        txtDeskripsi.setRows(5);
        jScrollPane3.setViewportView(txtDeskripsi);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 170, 300, 110));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(100, 90, 65));
        jLabel2.setText("Deskripsi Tugas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 130, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGIN (16).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarUserActionPerformed
        formLogin formLogin1= new formLogin();
        formLogin1.setVisible(true);  
        this.dispose();
    }//GEN-LAST:event_btnKeluarUserActionPerformed

    private void btnKeluarUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarUserMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnKeluarUserMouseClicked

    private void btnRefreshuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshuserActionPerformed
        cbNamamatkuluser.setSelectedIndex(0);
        cbPengurutan.setSelectedIndex(0);
        table();
    }//GEN-LAST:event_btnRefreshuserActionPerformed

    private void btnUrutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUrutActionPerformed

        try {
        // Ambil pilihan pengurutan dan nama mata kuliah dari ComboBox
            String sorting = cbPengurutan.getSelectedItem().toString();
            String selectedMatkul = cbNamamatkuluser.getSelectedItem().toString();

            Database.connect(); // Pastikan metode ini membuka koneksi ke database
            DefaultTableModel model = new DefaultTableModel();
            model.addColumn("ID Tugas");
            model.addColumn("Nama Mata Kuliah");
            model.addColumn("Nama Tugas");
            model.addColumn("Deskripsi Tugas");
            model.addColumn("Tenggat Waktu");
            model.addColumn("Skala Prioritas");
            model.addColumn("Status Tugas");

            try {
                String query = "SELECT * FROM tugas ";

                // Tambahkan filter mata kuliah jika user memilih mata kuliah tertentu
                if (!selectedMatkul.equals("Semua Mata Kuliah")) {
                    query += "WHERE nama_matkul = ? ";
                }

                // Tambahkan pengurutan berdasarkan pilihan user
                if (sorting.equals("Skala Prioritas Tinggi ke Rendah")) {
                    query += "ORDER BY skala_prioritas DESC";
                } else if (sorting.equals("Skala Prioritas Rendah ke Tinggi")) {
                    query += "ORDER BY skala_prioritas ASC";
                } else if (sorting.equals("Nama Tugas A-Z")) {
                    query += "ORDER BY nama_tugas ASC";
                } else if (sorting.equals("Nama Tugas Z-A")) {
                    query += "ORDER BY nama_tugas DESC";
                }

                PreparedStatement preparedStatement = Database.connection.prepareStatement(query);

                // Set parameter jika ada filter mata kuliah
                if (!selectedMatkul.equals("Semua Mata Kuliah")) {
                    preparedStatement.setString(1, selectedMatkul);
                }

                ResultSet resultSet = preparedStatement.executeQuery();

                while (resultSet.next()) {
                    model.addRow(new Object[]{
                        resultSet.getString("id_tugas"),
                        resultSet.getString("nama_matkul"),
                        resultSet.getString("nama_tugas"),
                        resultSet.getString("deskripsi_tugas"),
                        resultSet.getString("tenggat_waktu"),
                        resultSet.getString("skala_prioritas"),
                        resultSet.getString("status_tugas")
                    });
                }

                // Tampilkan data ke tabel
                tabelDaftartugasuser.setModel(model);

                // Jika tidak ada data ditemukan
                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(null, "Tidak ada data yang ditemukan.");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Terjadi Kesalahan saat mengambil data.");
                e.printStackTrace();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan koneksi.");
            e.printStackTrace();
        }
            
        
//        try {
//            String sorting = cbPengurutan.getSelectedItem().toString();
//            Database.connect();
//            DefaultTableModel model = new DefaultTableModel();
//            model.addColumn("ID Tugas");
//            model.addColumn("Nama Mata Kuliah");
//            model.addColumn("Nama Tugas");
//            model.addColumn("Deskripsi Tugas");
//            model.addColumn("Tenggat Waktu");
//            model.addColumn("Skala Prioritas");
//            model.addColumn("Status Tugas");
//            
//            try {
//                Statement statement = Database.connection.createStatement();
//                
//                String query = "SELECT * FROM tugas ORDER BY ";
//                if (sorting.equals("Skala Prioritas Tinggi ke Rendah")) {
//                    query += "skala_prioritas ASC";
//                } else if (sorting.equals("Skala Prioritas Rendah ke Tinggi")) {
//                    query += "skala_prioritas DESC";
//                } else if (sorting.equals("Nama Tugas A-Z")) {
//                    query += "nama_tugas ASC";
//                } else if (sorting.equals("Nama Tugas Z-A")) {
//                    query += "nama_tugas DESC";
//                }
//                
//                ResultSet resultSet = statement.executeQuery(query);
//                
//                while (resultSet.next()) {
//                    model.addRow(new Object[] {
//                        resultSet.getString("id_tugas"),
//                        resultSet.getString("nama_matkul"),
//                        resultSet.getString("nama_tugas"),
//                        resultSet.getString("deskripsi_tugas"),
//                        resultSet.getString("tenggat_waktu"),
//                        resultSet.getString("skala_prioritas"),
//                        resultSet.getString("status_tugas")
//                    });
//                    tabelDaftartugasuser.setModel(model);
//                }
//            } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
//            e.printStackTrace();
//        }
//            
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan");
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_btnUrutActionPerformed

    private void btnLihatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatActionPerformed
        try {
            DefaultTableModel model = new DefaultTableModel(new String[]{
                "ID Tugas", "Mata Kuliah", "Nama Tugas", "Deskripsi Tugas", "Tenggat Waktu", "Skala Prioritas", "Status"
            }, 0);

            tabelDaftartugasuser.setModel(model);
            String selectedMatkul = cbNamamatkuluser.getSelectedItem().toString(); // Ambil pilihan dari ComboBox
            
            String query;
        if (selectedMatkul.equals("Semua Mata Kuliah")) {
            // Query untuk menampilkan semua data
            query = "SELECT * FROM tugas";
            Database.preparedStatement = Database.connection.prepareStatement(query);
        } else {
            // Query untuk menampilkan data berdasarkan mata kuliah tertentu
            query = "SELECT * FROM tugas WHERE nama_matkul = ?";
            Database.preparedStatement = Database.connection.prepareStatement(query);
            Database.preparedStatement.setString(1, selectedMatkul);
        }

        Database.resultSet = Database.preparedStatement.executeQuery();
        
        
        // Tambahkan data hasil query ke JTable
        while (Database.resultSet.next()) {
            Object[] row = new Object[]{
                Database.resultSet.getInt("id_tugas"),
                Database.resultSet.getString("nama_matkul"),
                Database.resultSet.getString("nama_tugas"),
                Database.resultSet.getString("deskripsi_tugas"),
                Database.resultSet.getString("tenggat_waktu"),
                Database.resultSet.getString("skala_prioritas"),
                Database.resultSet.getString("status_tugas")
            };
            model.addRow(row);
        }

        // Jika tidak ada data ditemukan
        if (model.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Tidak ada data yang ditemukan.");
        }
            
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Terjadi kesalahan saat mengambil data.");
        e.printStackTrace();
        }
    }//GEN-LAST:event_btnLihatActionPerformed

    private void cbPengurutanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPengurutanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPengurutanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formDaftarTugasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formDaftarTugasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formDaftarTugasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formDaftarTugasUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formDaftarTugasUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKeluarUser;
    private javax.swing.JButton btnLihat;
    private javax.swing.JButton btnRefreshuser;
    private javax.swing.ButtonGroup btnTenggat;
    private javax.swing.JButton btnUrut;
    private javax.swing.JComboBox<String> cbNamamatkuluser;
    private javax.swing.JComboBox<String> cbPengurutan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabelDaftartugasuser;
    private javax.swing.JTextArea txtDeskripsi;
    // End of variables declaration//GEN-END:variables
}
